CREATE TABLE users(
	user_id INT PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(50) UNIQUE,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE,
    status VARCHAR(20) DEFAULT 'ACTICVE'
);

ALTER TABLE users
ADD CONSTRAINT chk_status
CHECK (status IN ('ACTIVE', 'INACTIVE'));

DROP TABLE users;